ALTER TABLE FACTURE 
ADD CONSTRAINT FK_FACTURE_num_ligue FOREIGN KEY (num_ligue) REFERENCES LIGUE (num_ligue); 
ALTER TABLE LIGNE_FACTURE 
ADD CONSTRAINT FK_LIGNE_FACTURE_num_ligue FOREIGN KEY (num_ligue) REFERENCES LIGUE (num_ligue);
ALTER TABLE LIGNE_FACTURE 
ADD CONSTRAINT FK_LIGNE_FACTURE_code_prestation FOREIGN KEY (code_prestation) REFERENCES PRESTATION (code_prestation);